### ISSUE TITLE
Reevaluate if the git-server folder should be in the repo

### ISSUE THREAD

**Issue by pmhsfelix** [i-on-project/integration#285]
Reevaluate if the git-server folder should be in the repo

**Comment by grimord** [comment]
Can probably be done through the [repos API](https://docs.github.com/en/rest/reference/repos#create-a-repository-for-the-authenticated-user). 

A possible solution would to create another service in the docker-compose file that exists solely to set the repository up once the git server is ready to handle http requests.

Something along the lines of :

```yaml
...

  gitsetup:
    image: gitbucket/gitbucket:4.35.3
    depends_on:
      git-server:
        condition: service_healthy
    restart: "no"
    entrypoint: [ "curl", "-X", "POST", "-u", "root:root", "localhost:8080/api/v3/user/repos", "-d", "'{"name":"integration_data"}'"]

...
```

Will give more info when able to test this solution appropriately.
