### ISSUE TITLE
Add curricular term to timetable output

### ISSUE THREAD

**Issue by grimord** [i-on-project/integration#292]
Add curicular term to each class produced on timetable exports.
ISEL's section naming convention allows this information to be extracted from the section name.

Regex format: `\b\D+(\d)\w+\b` -> curricular term can then be extracted from the capturing group. 
**Note:** This solution only works as long as curricular terms are single digit values. ISEL sections sometimes include a second digit which is only used when more than one section exists for the same term.

For example:
```yaml
...
classes:
- acr: "AApl"
  curricularTerm: 4
  sections:
  - section: "LI41D"
    events:
    - category: "LECTURE"
      location:
      - ""
      beginTime: "09:30"
      duration: "03:00"
      weekdays: "TU"
    instructors:
    - name: "Filipa Soares de Almeida"
      category: "LECTURE"
...

```
